INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (40, 4, 'Section 40–4 The Environment and Your Health
(pages 1049–1054)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (40, 3, 'Section 40–3 Immune System Disorders (pages 1043–1047)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (40, 2, 'Section 40–2 The Immune System (pages 1036–1042)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (40, 1, 'Section 40–1 Infectious Disease (pages 1031–1035)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (39, 4, 'Section 39–4 Fertilization and Development (pages 1016–1022)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (39, 3, 'Section 39–3 The Reproductive System (pages 1009–1015)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (39, 2, 'Section 39–2 Human Endocrine Glands (pages 1003–1008)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (39, 1, 'Section 39–1 The Endocrine System (pages 997–1002)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (38, 3, 'Section 38–3 The Excretory System (pages 985–989)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (38, 2, 'Section 38–2 The Process of Digestion (pages 978–984)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (38, 1, 'Section 38–1 Food and Nutrition (pages 971–977)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (37, 3, 'Section 37–3 The Respiratory System (pages 956–963)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (37, 1, 'Section 37–1 The Circulatory System (pages 943–950)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (36, 3, 'Section 36–3 The Integumentary System (pages 933–936)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (36, 2, 'Section 36–2 The Muscular System (pages 926–931)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (36, 1, 'Section 36–1 The Skeletal System (pages 921–925)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (35, 5, 'Section 35–5 Drugs and the Nervous System (pages 910–914)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (35, 4, 'Section 35–4 The Senses (pages 906–909)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (35, 3, 'Section 35–3 Divisions of the Nervous System (pages 901–905)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (35, 2, 'Section 35–2 The Nervous System (pages 897–900)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (35, 1, 'Section 35–1 Human Body Systems (pages 891–896)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (34, 2, 'Section 34–2 Patterns of Behavior (pages 878–882)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (34, 1, 'Section 34–1 Elements of Behavior (pages 871–876)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (33, 3, 'Section 33–3 Form and Function in Chordates (pages 857–864)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (33, 2, 'Section 33–2 Controlling Body Temperature (pages 854–856)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (33, 1, 'Section 33–1 Chordate Evolution (pages 849–852)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (32, 3, 'Section 32–3 Primates and Human Origins (pages 833–841)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (32, 2, 'Section 32–2 Diversity of Mammals (pages 828–832)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (32, 1, 'Section 32–1 Introduction to the Mammals (pages 821–827)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (31, 2, 'Section 31–2 Birds (pages 806–814)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (31, 1, 'Section 31–1 Reptiles (pages 797–805)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (30, 3, 'Section 30–3 Amphibians (pages 782–789)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (30, 2, 'Section 30–2 Fishes (pages 771–781)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (30, 1, 'Section 30–1 The Chordates (pages 767–770)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (29, 2, 'Section 29–2 Form and Function in Invertebrates (pages 751–758)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (29, 1, 'Section 29–1 Invertebrate Evolution (pages 745–750)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (28, 4, 'Section 28–4 Echinoderms (pages 734–738)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (28, 3, 'Section 28–3 Insects (pages 726–733)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (28, 2, 'Section 28–2 Groups of Arthropods (pages 720–725)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (28, 1, 'Section 28–1 Introduction to the Arthropods (pages 715–719)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (27, 4, 'Section 27–4 Mollusks (pages 701–708)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (27, 3, 'Section 27–3 Annelids (pages 694–699)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (27, 2, 'Section 27–2 Roundworms (pages 689–693)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (27, 2, 'Section 37–2 Blood and the Lymphatic System (pages 951–955)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (27, 1, 'Section 27–1 Flatworms (pages 683–688)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (26, 3, 'Section 26–3 Cnidarians (pages 669–675)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (26, 2, 'Section 26–2 Sponges (pages 664–667)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (26, 1, 'Section 26–1 Introduction to the Animal Kingdom (pages 657–663)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (25, 3, 'Section 25–3 Plant Adaptations (pages 643–646)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (25, 2, 'Section 25–2 Plant Responses (pages 639–642)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (25, 1, 'Section 25–1 Hormones and Plant Growth (pages 633–638)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (24, 3, 'Section 24–3 Plant Propagation and Agriculture (pages 622–626)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (24, 2, 'Section 24–2 Seed Development and Germination (pages 618–621)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (24, 1, 'Section 24–1 Reproduction With Cones and Flowers (pages 609–616)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (23, 5, 'Section 23–5 Transport in Plants (pages 599–602)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (23, 4, 'Section 23–4 Leaves (pages 595–598)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (23, 3, 'Section 23–3 Stems (pages 589–594)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (23, 2, 'Section 23–2 Roots (pages 584–588)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (23, 1, 'Section 23–1 Specialized Tissues in Plants (pages 579–583)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (22, 5, 'Section 22–5 Angiosperms—Flowering Plants (pages 569–572)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (22, 4, 'Section 22–4 Seed Plants (pages 564–568)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (22, 3, 'Section 22–3 Seedless Vascular Plants (pages 560–563)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (22, 2, 'Section 22–2 Bryophytes (pages 556–559)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (21, 3, 'Section 21–3 Ecology of Fungi (pages 537–542)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (21, 2, 'Section 21–2 Classification of Fungi (pages 530–536)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (21, 1, 'Section 21–1 The Kingdom Fungi (pages 527–529)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (21, 1, 'Section 22–1 Introduction to Plants (pages 551–555)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (20, 3, 'Section 20–3 Plantlike Protists: Unicellular Algae (pages 506–509)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (20, 2, 'Section 20–2 Animallike Protists: Protozoans (pages 499–505)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (20, 1, 'Section 20–1 The Kingdom Protista (pages 497–498)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (19, 3, 'Section 19-3 Diseases Caused by Bacteria and Viruses');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (19, 2, 'Section 19–2 Viruses (pages 478–483)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (19, 1, 'Section 19–1 Bacteria (pages 471–477)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (18, 2, 'Section 18–2 Modern Evolutionary Classification (pages 451–455)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (18, 1, 'Section 18–1 Finding Order in Diversity (pages 447–450)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (17, 3, 'Section 17–3 Evolution of Multicellular Life (pages 429–434)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (17, 2, 'Section 17–2 Earth’s Early History (pages 423–428)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (17, 1, 'Section 17–1 The Fossil Record (pages 417–422)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (16, 3, 'Section 16–3 The Process of Speciation (pages 404–410)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (16, 2, 'Section 16–2 Evolution as Genetic Change (pages 397–402)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (16, 1, 'Section 16–1 Genes and Variation (pages 393–396)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (15, 3, 'Section 15–3 Darwin Presents His Case (pages 378–386)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (15, 2, 'Section 15–2 Ideas That Shaped Darwin’s Thinking (pages 373–377)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (15, 1, 'Section 15–1 The Puzzle of Life’s Diversity (pages 369–372)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (14, 2, 'Section 14–2 Human Chromosomes (pages 349–353)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (14, 1, 'Section 14–1 Human Heredity (pages 341–348)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (13, 4, 'Section 13–4 Applications of Genetic Engineering (pages 331–333)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (13, 3, 'Section 13–3 Cell Transformation (pages 327–329)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (13, 2, 'Section 13–2 Manipulating DNA (pages 322–326)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (13, 1, 'Section 13–1 Changing the Living World (pages 319–321)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (12, 5, 'Section 12–5 Gene Regulation (pages 309–312)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (12, 4, 'Section 12–4 Mutations (pages 307–308)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (12, 3, 'Section 12–3 RNA and Protein Synthesis (pages 300–306)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (12, 2, 'Section 12–2 Chromosomes and DNA Replication (pages 295–299)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (12, 1, 'Section 12–1 DNA (pages 287–294)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (11, 5, 'Section 11–5 Linkage and Gene Maps (pages 279–280)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (11, 4, 'Section 11–4 Meiosis (pages 275–278)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (11, 3, 'Section 11–3 Exploring Mendelian Genetics (pages 270–274)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (11, 2, 'Section 11–2 Probability and Punnett Squares (pages 267–269)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (11, 1, 'Section 11–1 The Work of Gregor Mendel (pages 263–266)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (10, 3, 'Section 10–3 Regulating the Cell Cycle (pages 250–252)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (10, 2, 'Section 10–2 Cell Division (pages 244–249)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (10, 1, 'Section 10–1 Cell Growth (pages 241–243)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (9, 2, 'Section 9–2 The Krebs Cycle and Electron Transport (pages 226–232)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (9, 1, 'Section 9–1 Chemical Pathways (pages 221–225)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (8, 3, 'Section 8–3 The Reactions of Photosynthesis (pages 208–214)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (8, 2, 'Section 8–2 Photosynthesis: An Overview (pages 204–207)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (8, 1, 'Section 8–1 Energy and Life (pages 201–203)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (7, 4, 'Section 7–4 The Diversity of Cellular Life (pages 190–193)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (7, 3, 'Section 7–3 Cell Boundaries (pages 182–189)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (7, 2, 'Section 7–2 Eukaryotic Cell Structure (pages 174–181)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (7, 1, 'Section 7–1 Life Is Cellular (pages 169–173)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (6, 4, 'Section 6–4 Charting a Course for the Future (pages 157–160)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (6, 3, 'Section 6–3 Biodiversity (pages 150–156)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (6, 2, 'Section 6–2 Renewable and Nonrenewable Resources (pages 144–149)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (6, 1, 'Section 6–1 A Changing Landscape (pages 139–143)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (5, 3, 'Section 5–3 Human Population Growth (pages 129–132)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (5, 2, 'Section 5–2 Limits to Growth (pages 124–127)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (5, 1, 'Section 5–1 How Populations Grow (pages 119–123)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (4, 4, 'Section 4–4 Aquatic Ecosystems (pages 106–112)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (4, 3, 'Section 4–3 Biomes (pages 98–105)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (4, 2, 'Section 4–2 What Shapes an Ecosystem? (pages 90–97)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (4, 1, 'Section 4–1 The Role of Climate (pages 87–89)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (3, 3, 'Section 3–3 Cycles of Matter (pages 74–80)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (3, 2, 'Section 3–2 Energy Flow (pages 67–73)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (3, 1, 'Section 3–1 What Is Ecology? (pages 63–65)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (2, 4, 'Section 2–4 Chemical Reactions and Enzymes (pages 49–53)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (2, 3, 'Section 2–3 Carbon Compounds (pages 44–48)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (2, 2, 'Section 2–2 Properties of Water (pages 40–43)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (2, 1, 'Section 2–1 The Nature of Matter (pages 35–39)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (1, 4, 'Section 1–4 Tools and Procedures (pages 24–28)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (1, 3, 'Section 1–3 Studying Life (pages 16–22)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (1, 2, 'Section 1–2 How Scientists Work (pages 8–15)');
INSERT INTO BiologyAnswers.Sections (ChapterNumber, SectionNumber, SectionTitle) VALUES (1, 1, 'Section 1–1 What Is Science? (pages 3–7)');