<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'View\\' => array($baseDir . '/Application/View'),
    'Twig\\' => array($vendorDir . '/twig/twig/src'),
    'Tables\\' => array($baseDir . '/Application/Tables'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\DomCrawler\\' => array($vendorDir . '/symfony/dom-crawler'),
    'Symfony\\Component\\Debug\\' => array($vendorDir . '/symfony/debug'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Symfony\\Component\\BrowserKit\\' => array($vendorDir . '/symfony/browser-kit'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Model\\' => array($baseDir . '/Application/Model'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Google\\Cloud\\Utils\\' => array($vendorDir . '/google/cloud-tools/src/Utils'),
    'Google\\Cloud\\TestUtils\\' => array($vendorDir . '/google/cloud-tools/src/TestUtils'),
    'Google\\Cloud\\' => array($vendorDir . '/google/cloud/src'),
    'Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Facebook\\' => array($vendorDir . '/facebook/graph-sdk/src/Facebook'),
    'Controller\\' => array($baseDir . '/Application/Controller'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Carbon\\Interfaces\\' => array($vendorDir . '/richardtmiles/carbonphp/Interfaces'),
    'Carbon\\Helpers\\' => array($vendorDir . '/richardtmiles/carbonphp/Helpers'),
    'Carbon\\Error\\' => array($vendorDir . '/richardtmiles/carbonphp/Error'),
    'Carbon\\' => array($vendorDir . '/richardtmiles/carbonphp/Structure'),
);
