REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('1','Chapter 1 The Science of Biology');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('2','Chapter 2 The Chemistry of Life');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('3','Chapter 3 The Biosphere');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('4','Chapter 4 Ecosystems and Communities');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('5','Chapter 5 Populations');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('6','Chapter 6 Humans in the Biosphere');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('7','Chapter 7 Cell Structure and Function');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('8','Chapter 8 Photosynthesis');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('9','Chapter 9 Cellular Respiration');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('10','Chapter 10 Cell Growth and Division');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('11','Chapter 11 Introduction to Genetics');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('12','Chapter 12 DNA and RNA');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('13','Chapter 13 Genetic Engineering');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('14','Chapter 14 The Human Genome');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('15','Chapter 15 Darwin’s Theory of Evolution');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('16','Chapter 16 Evolution of Populations');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('17','Chapter 17 The History of Life');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('18','Chapter 18 Classification');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('19','Chapter 19 Bacteria and Viruses');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('20','Chapter 20 Protists');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('21','Chapter 21 Fungi');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('22','Chapter 22 Plant Diversity');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('23','Chapter 23 Roots, Stems, and Leaves');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('24','Chapter 24 Reproduction of Seed Plants');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('25','Chapter 25 Plant Responses and Adaptations');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('26','Chapter 26 Sponges and Cnidarians');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('27','Chapter 27 Worms and Mollusks');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('28','Chapter 28  Arthropods and Echinoderms');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('29','Chapter 29 Comparing Invertebrates');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('30','Chapter 30 Nonvertebrate Chordates, Fishes, and Amphibians');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('31','Chapter 31 Reptiles and Birds');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('32','Chapter 32 Mammals');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('33','Chapter 33 Comparing Chordates');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('34','Chapter 34 Animal Behavior');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('35','Chapter 35 Nervous System');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('36','Chapter 36 Skeletal, Muscular, and Integumentary Systems');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('37','Chapter 37 Missing');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('38','Chapter 38 Digestive and Excretory Systems');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('39','Chapter 39 Endocrine and Reproductive Systems');
REPLACE INTO BiologyAnswers.Chapters (ChapterNumber, ChapterTitle) VALUES ('40','Chapter 40 The Immune System and Disease');
